# Fichero de configuraci贸n para los contenedores del cliente de la aplicaci贸n CarShare
version: "3.8"
services:
  # Crea un contenedor con la api de la aplicaci贸n
  envtest:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: envtest
    # Para la versi贸n de desarrollo se mapea la carpeta con una local
    ports: 
      - 4000:4200
    volumes:
      - .:/usr/src/app
    networks:
      - envtest
networks:
    envtest:
        driver: bridge
